title: PyKEEN
author: PyKEEN Project Team
description: >
  Predictions for the People

twitter_username: keenuniverse
github_username:  pykeen

show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
